### ISSUE TITLE
Center coordinate issue

### ISSUE THREAD

**Issue by elwoodhouse** [ghettovoice/vuelayers-demo#1]
Hi Vladamir,

I've been playing around with your app, very nice work. 

I think there is an issue with the starting position of the map as no matter what I set as part of the center coordinates (eg center: [145, -37]) it always starts the map at [0, 0].

Is this a problem with the demo app or the vuelayers code? I'll have a look into it but thought you might find it before I track can track it down.

Thanks,
Leon.

**Comment by ghettovoice** [comment]
Hi @elwoodhouse,
thank you for attention!
The problem was with demo app: an old beta version of vuelayers was used.
I upgrade demo, now all works as expected.
Thank you!
