### ISSUE TITLE
trying run serve - master branch

### ISSUE THREAD

**Issue by Bear4** [ghettovoice/vuelayers-demo#14]
Very interesting project, congratulations!

run from master-branch:
get error:
This relative module was not found:
* ./assets/pacman.geojson in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Map.vue?vue&type=script&lang=js&

 and npm run lint:
> vuelayers-demo@0.1.0 lint
> vue-cli-service lint

```
error: 'selection' is defined but never used (vue/no-unused-vars) at src/components/Map.vue:163:29:
  161 |       v-if="drawType == null"
  162 |       :features.sync="selectedFeatures">
> 163 |       <template slot-scope="selection">
      |                             ^
  164 |         <!-- select styles -->
  165 |         <VlStyle>
  166 |           <VlStyleStroke


error: 'loadingBBox' is not defined (no-undef) at src/components/Map.vue:583:22:
  581 |             },
  582 |             strategyFactory() {
> 583 |               return loadingBBox
      |                      ^
  584 |             },
  585 |           },
  586 |         },
```

[ add packman.geojson etc. from v.0.11.x ]

And run from v.0.11.x

npm ERR! code 1
npm ERR! path /home/bear/vue-layers-demo/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /home/bear/.nvm/versions/node/v16.2.0/bin/node /home/bear/vue-layers-demo/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! make: Wejście do katalogu '/home/bear/vue-layers-demo/node_modules/node-sass/build'
npm ERR!   g++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DLIBSASS_VERSION="3.5.4"' -I/home/bear/.node-gyp/16.2.0/include/node -I/home/bear/.node-gyp/16.2.0/src -I/home/bear/.node-gyp/16.2.0/deps/openssl/config -I/home/bear/.node-gyp/16.2.0/deps/openssl/openssl/include -I/home/bear/.node-gyp/16.2.0/deps/uv/include -I/home/bear/.node-gyp/16.2.0/deps/zlib -I/home/bear/.node-gyp/16.2.0/deps/v8/include -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -std=gnu++14 -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp
npm ERR!   g++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DLIBSASS_VERSION="3.5.4"' -I/home/bear/.node-gyp/16.2.0/include/node -I/home/bear/.node-gyp/16.2.0/src -I/home/bear/.node-gyp/16.2.0/deps/openssl/config -I/home/bear/.node-gyp/16.2.0/deps/openssl/openssl/include -I/home/bear/.node-gyp/16.2.0/deps/uv/include -I/home/bear/.node-gyp/16.2.0/deps/zlib -I/home/bear/.node-gyp/16.2.0/deps/v8/include -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -std=gnu++14 -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast_fwd_decl.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast_fwd_decl.o ../src/libsass/src/ast_fwd_decl.cpp
npm ERR!   g++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DLIBSASS_VERSION="3.5.4"' -I/home/bear/.node-gyp/16.2.0/include/node -I/home/bear/.node-gyp/16.2.0/src -I/home/bear/.node-gyp/16.2.0/deps/openssl/config -I/home/bear/.node-gyp/16.2.0/deps/openssl/openssl/include -I/home/bear/.node-gyp/16.2.0/deps/uv/include -I/home/bear/.node-gyp/16.2.0/deps/zlib -I/home/bear/.node-gyp/16.2.0/deps/v8/include -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -std=gnu++14 -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/backtrace.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/backtrace.o ../src/libsass/src/backtrace.cpp
...
...
...                                ^~~
npm ERR! /home/bear/.node-gyp/16.2.0/include/node/v8.h:3929:37: note:   candidate expects 3 arguments, 2 provided
npm ERR! make: *** [binding.target.mk:133: Release/obj.target/binding/src/binding.o] Błąd 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/home/bear/vue-layers-demo/node_modules/node-gyp/lib/build.js:262:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 5.8.0-59-generic
npm ERR! gyp ERR! command "/home/bear/.nvm/versions/node/v16.2.0/bin/node" "/home/bear/vue-layers-demo/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /home/bear/vue-layers-demo/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.2.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:

**Comment by ghettovoice** [comment]
Hello @Bear4 ,
version from `master` branch is currently not complete. 
So you should switch to the `v0.11.x` branch. 
As for the error, I guess, you should try to remove `node_modules` and re-install after switching to `v0.11.x` branch. And also I recommend to run the app on the node v0.14.x that is LTS version for now. If I'm not wrong there was similar problems with installing/building of `node-sass` on node v0.16
