### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by xdursoc** [ghettovoice/vuelayers-demo#3]
Hi, 
I'm searching to use VueLayers but as probably it is known there is a lack of documentation. There is a way to select an object (the flag for example) and launch in a direct manner a function of my js ?

Regards,

Christian

**Comment by ghettovoice** [comment]
Hi @xdursoc ,
take a look at this demo https://jsfiddle.net/ghettovoice/qcrjzdwn/

**Comment by xdursoc** [comment]
hi, thanks a lot for the reply!

**Comment by xdursoc** [comment]
Hi, It is possible to set a minimum and maximum value of zoom? It is possible to avoid the map replication?

**Comment by ghettovoice** [comment]
Min/Max zoom can be defined on `vl-view` component. `<vl-view :min-zoom="..." :max-zoom="..." />`.

Don't get what you mean as "map replication"? Describe what you trying to implement.

**Comment by xdursoc** [comment]
Hi @ghettovoice When I zoom out I see the map replicated as you can see in the demo of the Vue Layers you have two flags, circles etc..., I'm just implementing the visualization of the map of the world

**Comment by ghettovoice** [comment]
@xdursoc now I got it 😅 
almost each source have `wrap-x` prop, which is `true` by default.
So for example:

```html
<vl-layer-tile>
  <vl-source-osm :wrap-x="false" />
</vl-layer-tile>
```

will render only one Earth map

**Comment by xdursoc** [comment]
oh perfect, thanks a lot! @ghettovoice

**Comment by xdursoc** [comment]
the strange thing @ghettovoice is that the map is not replicated now ;) , but the object (flag, circles etc...) they continue to be replicated....

**Comment by ghettovoice** [comment]
Try to add `:wrap-x="false"` to the `vl-map` too.

**Comment by xdursoc** [comment]
yeah it works TOP! @ghettovoice

**Comment by xdursoc** [comment]
@ghettovoice in your opinion, it is possible to zoom on selected object (point, flag?)

**Comment by ghettovoice** [comment]
Here is the demo with feature fit on select https://jsfiddle.net/ghettovoice/mLzqwk03/.
Take a look on `onSelect` handler.

**Comment by xdursoc** [comment]
Sorry @ghettovoice but I don't see any kind of object in your map :(

**Comment by ghettovoice** [comment]
Jsfiddle now by default uses in-broser console, that triggers a lot of errors and prevents onSelect handler to work correctly. Try to disable it and re-run example.

![image](https://user-images.githubusercontent.com/4323000/83630273-37f14600-a5a4-11ea-971f-cf3fe1e7dd77.png)

As for zoom as close as possible, you can try to play around `fit` options, here is description https://openlayers.org/en/v5.3.0/apidoc/module-ol_View-View.html#fit. You probably need to use `constrainResolution` and `nearest `

**Comment by xdursoc** [comment]
Yeah in jsfiddle works now, in my js code I have Uncaught ReferenceError: _ is not defined it's a dependency missing?

**Comment by xdursoc** [comment]
Hi @ghettovoice sorry, I'm a nightmare. I'm trying to understand how it works, I have a strange behaviour with the watch function I think, because when it starts it is not smooth, it pulses :(

**Comment by ghettovoice** [comment]
> I see that in your example you have a GeoJSON to describe the points etc..., in my case no. Is this the problem?
i don't think this is a problem, sure if you don't render hundreds of features with vl-feature component.

From you sample I can't say anything why it's not smooth, show me a full component code.

**Comment by xdursoc** [comment]
```html
      <div id="map">
        <!--MAPPA-->
        <vl-map
          ref="map"
          data-projection="EPSG:4326"
          :wrap-x="false"
          @click="clickCoordinate = $event.coordinate"
        >
          <vl-view
            ref="mapView"
            :zoom.sync="zoom"
            :center.sync="center"
            :min-zoom.sync="minZoom"
          ></vl-view>

          <vl-layer-tile id="osm">
            <vl-source-osm :wrap-x ="false"></vl-source-osm>
          </vl-layer-tile>

         <vl-layer-vector>
            <vl-source-vector ref="geoSource" :features.sync="features" :wrap-x="false">
              <vl-feature :id="project.id" v-for="(project, index) in projectList">
                <vl-geom-point :coordinates="[7.679443, 45.058 + index*0.75]"></vl-geom-point>
                <vl-style-box>
                  <vl-style-icon src="https://vuelayers.github.io/demo/img/flag.b922504.png" :scale="0.40" :anchor="[0.1, 0.95]" :size="[128, 128]"></vl-style-icon>
                </vl-style-box>
            </vl-feature>
            </vl-source-vector>
          </vl-layer-vector>

         <vl-interaction-select
            :features.sync="selectedFeatures"
            @select="mapSelect"
            @unselect="mapUnselect"
          >
            <template slot-scope="select">
              <!-- select styles -->
              <vl-style-box>
                <vl-style-stroke color="#423e9e" :width="7"></vl-style-stroke>
                <vl-style-fill :color="[254, 178, 76, 0.7]"></vl-style-fill>
                <vl-style-circle :radius="5">
                  <vl-style-stroke color="#423e9e" :width="7"></vl-style-stroke>
                  <vl-style-fill :color="[254, 178, 76, 0.7]"></vl-style-fill>
                </vl-style-circle>
              </vl-style-box>
              <vl-style-box :z-index="1">
                <vl-style-stroke color="#d43f45" :width="2"></vl-style-stroke>
                <vl-style-circle :radius="5">
                  <vl-style-stroke color="#d43f45" :width="2"></vl-style-stroke>
                </vl-style-circle>
              </vl-style-box>
              <!--// select styles -->
            </template>
          </vl-interaction-select>

.......................continue
```

**Comment by xdursoc** [comment]
```javascript
new Vue({
    el: "#projects-page-container",
    data: {
      projectList: [],
      projectId: null,

      zoom: 5,
      center: [7.679443, 45.058],
      rotation: 0,
      features: [],
      selectedFeatures: [],
      mapVisible: true,
      clickCoordinate: undefined,
      projectSelectedList: [],
      minZoom: 2,
},
    watch: {
      features: _.debounce(function () {
        this.$refs.mapView.$view.fit(this.$refs.geoSource.$source.getExtent(), {
          duration: 1000,
        });
      }, 100),
    },

.....other methods........
the selection zoom works...It's the first one (managed by the watch function that does not work I think...)
```

**Comment by xdursoc** [comment]
@ghettovoice in my opinion I have a problem of data, because they are loaded to the source asynchronously. I take the projects when CREATED with an ajax function.

**Comment by ghettovoice** [comment]
I guess your watcher triggers multiple times, probably while previous animation is still running.
Try to stop any currently active animations before start new one. Add at the start of your watcher: `this.$refs.mapView.$view.cancelAnimations()`

**Comment by xdursoc** [comment]
@ghettovoice like this:
```javascript
  watch: {
    features: _.debounce(function () {
      this.$refs.mapView.$view.cancelAnimations();
      this.$refs.mapView.$view.fit(this.$refs.geoSource.$source.getExtent(), {
        duration: 1000,
      });
    }, 100),
  },
```

**Comment by ghettovoice** [comment]
yes

**Comment by xdursoc** [comment]
nope, it seems the situation is a little better, but the problem is the same. The problem is still present when I click on my object. The strange thing is that I added a zoom button that recall the same function of the watcher and it works correctly, smooth and precise, thant I click to my flag and I can zoom in my project. But if I use the function in the watcher the initial zoom does not work correctly as the selection of the flag.

**Comment by ghettovoice** [comment]
Because on select, you probably get 2 parallel fit animations. Try to rewrite watcher with this one:
```js
watch: {
    features: _.debounce(function (value, prev) {
      if (_.isEqual(value, prev)) return // check that value truly was changed
      this.$refs.mapView.$view.cancelAnimations();
      this.$refs.mapView.$view.fit(this.$refs.geoSource.$source.getExtent(), {
        duration: 1000,
      });
    }, 100),
  },
```

**Comment by xdursoc** [comment]
Perfect, it worksssss!

**Comment by xdursoc** [comment]
Hi, @ghettovoice , I have a question for you. There is a way to set the limit zoom on a value able to have the map that fit (at this maximum value of zoom) its container?

**Comment by ghettovoice** [comment]
@xdursoc fit method support definition of zoom constraints, see `maxZoom`/`minResolution` options here https://openlayers.org/en/v5.3.0/apidoc/module-ol_View-View.html#fit

**Comment by xdursoc** [comment]
thanks @ghettovoice I will try on the next days, I hope it will work

**Comment by xdursoc** [comment]
Hi @ghettovoice in wich way can I insert the default (or custom) control in the map with vuelayers? (Like ZoomtoExtent ecc...)

**Comment by ghettovoice** [comment]
Example on jsfiddle uses umd version of the ol package, this why in browser exists `ol` global variable. 
When you write single file Vue components, you should import from the `ol` package. 

For example  to add any std controls:
https://openlayers.org/en/v5.3.0/apidoc/module-ol_control.html
```
<template>
  <vl-map : default-controls="mapControls">
    ...
  </vl-map>
</template>

<script>
import { defaults, ScaleLine } from 'ol/control'

export default {
  data () {
    return {
      mapControls: defaults().extend([
        new ScaleLine(),
        ....
      ]),
    }
  },
}
</script>
```

Transform projection functions are available inside `ol/proj` package https://openlayers.org/en/v5.3.0/apidoc/module-ol_proj.html

```
import {.fromLonLat, toLonLat } from 'ol/proj'
```

**Comment by xdursoc** [comment]
Ok, and in my case, I need to convert this, in which way can I convert the syntax?
this.currentPosition = ol.proj.transform(hitFeature.getGeometry().getCoordinates(), 'EPSG:3857', 'EPSG:4326')

**Comment by ghettovoice** [comment]
> in my case, I need to convert this, in which way can I convert the syntax?

```
import { transform } from 'ol/proj'

this.currentPosition = transform(hitFeature.getGeometry().getCoordinates(), 'EPSG:3857', 'EPSG:4326')
```

> For the control I follow your demo, but for the zoomslider I have this error:
ZoomSlider.js?1e00:204 Uncaught TypeError: this.getMap(...).getView(...).beginInteraction is not a function
at ZoomSlider.handleDraggerStart_

> and for OverviewMap:
Vue warn]: Error in v-on handler: "TypeError: view.calculateExtentInternal is not a function"
TypeError: view.calculateExtentInternal is not a function

Seems like you are using wrong version of the `ol` package. Current stable `vuelayers` works with `ol@5.x.x` version.
You probably install `ol@6.x.x` manually and now VueLayers uses it's own separatly installed `ol`. 
To fix this, drop `node_modules` directory, and change `ol` version to any of `5.x.x`, then run `npm install`

**Comment by xdursoc** [comment]
Thanks @ghettovoice the controls work now. But I don't understand in how to use 
this.currentPosition = ol.proj.transform(hitFeature.getGeometry().getCoordinates(), 'EPSG:3857', 'EPSG:4326')
in which way I need to replace ol in this expression?

**Comment by ghettovoice** [comment]
import `transform` function from 'ol/proj'.

```
import { transform } from 'ol/proj'

...

this.currentPosition = transform(hitFeature.getGeometry().getCoordinates(), 'EPSG:3857', 'EPSG:4326')
```

**Comment by xdursoc** [comment]
Ok it works @ghettovoice ! Thanks a lot

**Comment by ghettovoice** [comment]
they position through css, so just override any styles you want

**Comment by xdursoc** [comment]
Thanks! @ghettovoice

**Comment by xdursoc** [comment]
Hi @ghettovoice I tried to use css to move the controls in the map but I'm not able to it, I'm trying to reproduce the map2 of the ol example (https://openlayers.org/en/latest/examples/zoomslider.html). I have a <vl-map id=map ref =map> tag and I wrote for css:
```CSS3
      /**
       * The zoomslider in the map shall be placed between the zoom-in and
       * zoom-out buttons.
       */
      #map .ol-zoom .ol-zoom-out {
        margin-top: 204px;
      }
      #map .ol-zoomslider {
        background-color: transparent;
        top: 2.3em;
      }

      #map .ol-touch .ol-zoom .ol-zoom-out {
        margin-top: 212px;
      }
      #map .ol-touch .ol-zoomslider {
        top: 2.75em;
      }

      #map .ol-zoom-in.ol-has-tooltip:hover [role=tooltip],
      #map .ol-zoom-in.ol-has-tooltip:focus [role=tooltip] {
        top: 3px;
      }

      #map .ol-zoom-out.ol-has-tooltip:hover [role=tooltip],
      #map .ol-zoom-out.ol-has-tooltip:focus [role=tooltip] {
        top: 232px;
      }
```
but the controls are not changing position, any suggustions?

**Comment by ghettovoice** [comment]
Try add `!important`. If it works, you probably have a mess of styles, so original style overrides your.
Or you missed something in css selector, check through Chrome dev console, what styles applied.

```css
#map .ol-zoomslider {
       background-color: transparent !important;
       top: 2.3em !important;
}
...
```

**Comment by xdursoc** [comment]
I used 
::v-deep .ol-zoom .ol-zoom-out {
  margin-top: 204px;
}
.....
and it works @ghettovoice

**Comment by ghettovoice** [comment]
Ok. Yes, you need deep selector with css modules enabled.

**Comment by xdursoc** [comment]
Hi @ghettovoice, There exist a way to have an overlay menu like: https://viglino.github.io/ol-ext/examples/control/map.control.overlay.menu.html

Thanks in advance.

**Comment by ghettovoice** [comment]
There is example with appending ol-ext component (not you need, but you can use same way) https://jsfiddle.net/ghettovoice/ryj59Lbk/
