### ISSUE TITLE
Missing pacman.geojson

### ISSUE THREAD

**Issue by mattsmasterplan** [ghettovoice/vuelayers-demo#4]
After running npm install, unable to compile application due to error of missing geojson. Page is 404'd on github.

![image](https://user-images.githubusercontent.com/55507507/104391580-2b57a780-550e-11eb-9c45-5c711563644f.png)

**Comment by ghettovoice** [comment]
Hello @mattsmasterplan ,
I guess you clone this repo, so you need to switch to v0.11.x branch. Currently in master branch I start migrating to v0.12
